/**
 * optimization_space_v2.ts
 *
 * Catálogo de campos deducibles del F22 AT2026.
 * GENERADO AUTOMÁTICAMENTE el 2026-03-17 desde instrucciones_unidas.pdf
 * usando Claude AI + reglas CSW (72 campos identificados).
 *
 * Distribución por tipo de límite:
 * - fixed_pesos: 3 campos
 * - fixed_uf: 3 campos
 * - fixed_utm: 1 campos
 * - none: 58 campos
 * - percentage_of_field: 2 campos
 * - percentage_of_income: 5 campos
 *
 * NO EDITAR MANUALMENTE — regenerar con:
 *   python3 scripts/1_extract_chunks.py
 *   python3 scripts/2_enrich_with_ai.py
 *   python3 scripts/3_generate_ts.py
 */

export interface DeductibleField {
  fieldCode: number;
  name: string;
  legalBasis: string;
  limitType: "fixed_utm" | "fixed_uf" | "fixed_pesos" | "percentage_of_income" | "percentage_of_field" | "none";
  limitValue?: number;
  referenceField?: number;
  paramId?: number;
  strategy: string;
  /** Quién puede usar esta deducción (null = todos). */
  conditions?: string;
}

export const DEDUCTIBLE_FIELDS: DeductibleField[] = [
  {
    fieldCode: 365,
    name: "Crédito por impuesto territorial",
    legalBasis: "artículo 20, N° 1, letra a), de la LIR",
    limitType: "none",
    strategy: "Aprovechar el crédito por impuesto territorial para reducir la carga tributaria en la explotación de bienes raíces agrícolas y no agrícolas.",
    conditions: "Contribuyentes que exploten bienes raíces agrícolas o no agrícolas en calidad de propietarios o usufructuarios.",
  },
  {
    fieldCode: 366,
    name: "Crédito por bienes físicos del activo inmovilizado",
    legalBasis: "artículo 33 bis de la LIR",
    limitType: "none",
    strategy: "Considera adquirir bienes físicos del activo inmovilizado para aprovechar el crédito tributario disponible. Asegúrate de que los bienes sean nuevos y depreciables.",
    conditions: "Contribuyentes que declaran el IDPC en las líneas 54, 55 o 56 del F-22",
  },
  {
    fieldCode: 392,
    name: "Crédito por rentas de zona franca",
    legalBasis: "artículo 23 del DS Nº 341 de 1977",
    limitType: "percentage_of_income",
    limitValue: 0.27,
    strategy: "Aprovechar el crédito por IDPC para optimizar la carga tributaria de las rentas obtenidas en zonas francas.",
    conditions: "Contribuyentes que desarrollen actividades dentro de zonas francas.",
  },
  {
    fieldCode: 465,
    name: "Gastos efectivos",
    legalBasis: "artículo 31 de la LIR",
    limitType: "none",
    referenceField: 547,
    strategy: "Registrar los gastos efectivos incurridos en la actividad para rebajar del ingreso bruto anual. Asegurarse de que los gastos cumplan con los requisitos establecidos en la LIR.",
    conditions: "Contribuyentes que opten por rebajar gastos efectivos",
  },
  {
    fieldCode: 494,
    name: "Gastos presuntos",
    legalBasis: "Ley N° 16.282, DL N° 45 de 1973",
    limitType: "fixed_utm",
    limitValue: 15,
    referenceField: 547,
    strategy: "Considera los gastos presuntos para optimizar tu carga tributaria, asegurándote de no exceder el límite establecido. Evalúa si es más beneficioso optar por gastos presuntos o gastos efectivos.",
    conditions: "Contribuyentes que optan por rebajar de ingresos brutos actualizados los gastos presuntos.",
  },
  {
    fieldCode: 702,
    name: "Ahorro neto positivo utilizado en el ejercicio",
    legalBasis: "Ley sobre Impuesto a la Renta (LIR)",
    limitType: "fixed_pesos",
    limitValue: 54242760,
    strategy: "Considerar el ahorro neto positivo para optimizar el cálculo del crédito fiscal.",
    conditions: "Contribuyentes del IGC e IUSC que perciban rentas del artículo 42, N° 1 de la LIR.",
  },
  {
    fieldCode: 770,
    name: "Ahorro Previsional Voluntario",
    legalBasis: "artículo 42 bis LIR",
    limitType: "fixed_uf",
    limitValue: 600,
    strategy: "Aprovechar al máximo el ahorro previsional para reducir la carga tributaria. Asegúrate de realizar los depósitos dentro del año calendario para beneficiarte de la deducción.",
    conditions: "Contribuyentes del artículo 42, N° 2 de la LIR",
  },
  {
    fieldCode: 830,
    name: "Crédito IEAM utilizado en el ejercicio",
    legalBasis: "artículo 60 de la LIR",
    limitType: "none",
    strategy: "Aprovechar el crédito IEAM para reducir la carga tributaria en el impuesto a la renta. Es recomendable llevar un control adecuado de los créditos disponibles para su correcta imputación.",
    conditions: "Contribuyentes que hayan registrado el monto del crédito en el código 828",
  },
  {
    fieldCode: 839,
    name: "Remanente de crédito por bienes físicos",
    legalBasis: "artículo 4° transitorio de la Ley N° 19.578",
    limitType: "none",
    strategy: "Aprovechar el remanente de crédito por inversiones en activos fijos para reducir la carga tributaria en años futuros.",
    conditions: "Contribuyentes que tenían derecho al crédito por inversiones en activos fijos hasta el 31 de diciembre de 2014.",
  },
  {
    fieldCode: 850,
    name: "Rebaja por presunción de asignación de zona",
    legalBasis: "artículo 13 del DL N° 889 de 1975",
    limitType: "fixed_pesos",
    strategy: "Los contribuyentes en zonas extremas pueden deducir una parte de la gratificación de zona de sus rentas de segunda categoría. Es recomendable calcular la deducción mensual según los honorarios y gastos efectivos para maximizar el beneficio.",
    conditions: "Contribuyentes del artículo 42, N° 2 de la LIR que residan en zonas extremas",
  },
  {
    fieldCode: 872,
    name: "Gastos por donaciones para fines sociales",
    legalBasis: "artículo 1° bis Ley N° 19.885 y artículo 26 Ley N° 21.450",
    limitType: "percentage_of_income",
    limitValue: 0.2,
    referenceField: 547,
    strategy: "Aprovechar al máximo las donaciones para fines sociales para optimizar la carga tributaria. Considerar el total de donaciones para calcular el límite de gasto deducible.",
    conditions: "Contribuyentes del artículo 42, N° 2, de la LIR que declaran ingresos y gastos efectivos",
  },
  {
    fieldCode: 930,
    name: "Cuota exenta 10 UTA",
    legalBasis: "N° 5 de la letra A) del ex artículo 57 bis de la LIR",
    limitType: "fixed_pesos",
    limitValue: 8345040,
    strategy: "Aprovechar la cuota exenta de 10 UTA si se ha mantenido un saldo de ahorro neto positivo durante cuatro años tributarios consecutivos.",
    conditions: "Contribuyentes que han declarado un saldo de ahorro neto positivo durante cuatro años tributarios consecutivos.",
  },
  {
    fieldCode: 950,
    name: "Total depreciación normal de bienes con depreciación acelerada",
    legalBasis: "artículo 31 de la LIR",
    limitType: "none",
    strategy: "Considerar la depreciación normal para optimizar la carga tributaria en el activo inmovilizado.",
    conditions: "Contribuyentes que opten por depreciación acelerada según los regímenes establecidos.",
  },
  {
    fieldCode: 984,
    name: "Otras rebajas especiales",
    legalBasis: "DL N° 1.089 de 1975",
    limitType: "none",
    strategy: "Los contribuyentes pueden registrar créditos especiales por diferencias de tasa del IDPC en este código para reducir su carga tributaria.",
    conditions: "Contribuyentes que celebren contratos con el Estado de Chile sobre exploración y explotación de yacimientos de hidrocarburos.",
  },
  {
    fieldCode: 1056,
    name: "Valor de adquisición de bienes raíces reajustados",
    legalBasis: "artículo 17 de la LIR",
    limitType: "none",
    strategy: "Registrar el valor de adquisición de bienes raíces reajustados para disminuir la base imponible en la enajenación de estos activos.",
    conditions: "Aplicable a bienes raíces adquiridos entre el 1° de enero de 2004 y el 28 de septiembre de 2014, cumpliendo con los requisitos de la Ley N° 20.780.",
  },
  {
    fieldCode: 1058,
    name: "Mayor o menor valor percibido o devengado",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Registrar correctamente el mayor valor para deducir pérdidas en la declaración de impuestos.",
    conditions: "Aplicable a contribuyentes que registren pérdidas en sus ingresos.",
  },
  {
    fieldCode: 1140,
    name: "Arriendos pagados o adeudados",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar los arriendos como un gasto necesario para el desarrollo del giro del negocio, asegurando que estén debidamente documentados.",
    conditions: "Contribuyentes que tengan arriendos de bienes raíces agrícolas o no agrícolas destinados al desarrollo de su giro.",
  },
  {
    fieldCode: 1141,
    name: "Gastos por exigencias medio ambientales",
    legalBasis: "Circular N° 53 de 2020",
    limitType: "none",
    strategy: "Considerar los gastos relacionados con exigencias medioambientales para optimizar la carga tributaria. Asegurarse de que los gastos estén debidamente documentados y aprobados por la autoridad competente.",
    conditions: "Aplicable a proyectos o actividades con resolución de aprobación ambiental",
  },
  {
    fieldCode: 1142,
    name: "Gasto por indemnización o compensación a clientes",
    legalBasis: "artículo 31, N° 14 de la LIR",
    limitType: "none",
    strategy: "Considerar los desembolsos y descuentos pagados por indemnización a clientes como deducibles para reducir la carga tributaria. Asegurarse de documentar adecuadamente los pagos realizados en cumplimiento de obligaciones legales.",
    conditions: "Contribuyentes que realicen desembolsos por indemnización o compensación a clientes o usuarios.",
  },
  {
    fieldCode: 1147,
    name: "Costos y gastos asociados a ingresos no renta",
    legalBasis: "art. 17 LIR",
    limitType: "none",
    strategy: "Registrar los costos y gastos asociados a ingresos no renta para optimizar la declaración de impuestos.",
    conditions: "Contribuyentes que generan ingresos no renta.",
  },
  {
    fieldCode: 1148,
    name: "Proporcionalidad gastos imputados a ingresos no renta y/o rentas exentas",
    legalBasis: "artículo 33, N° 1, letra e) de la LIR",
    limitType: "none",
    strategy: "Considerar los gastos y desembolsos que se imputan a ingresos no renta y rentas exentas para optimizar la carga tributaria.",
    conditions: "Contribuyentes que imputen gastos a ingresos no renta y/o rentas exentas.",
  },
  {
    fieldCode: 1152,
    name: "Gastos adeudados por cambio de régimen",
    legalBasis: "artículo 14, letra D), N° 3 o N° 8 de la LIR",
    limitType: "none",
    strategy: "Considerar los gastos adeudados al 31.12.2024 para optimizar la carga tributaria al cambiar de régimen.",
    conditions: "Contribuyentes acogidos al régimen del artículo 14, letra D), N° 3 o N° 8 de la LIR que cambian al régimen del artículo 14 letra A).",
  },
  {
    fieldCode: 1154,
    name: "Incentivo al ahorro según art. 14 letra E) LIR",
    legalBasis: "artículo 14, letra E) de la LIR",
    limitType: "fixed_uf",
    limitValue: 5000,
    strategy: "Considerar el monto deducido de la RLI que se mantenga invertido en la empresa para maximizar el beneficio fiscal.",
    conditions: "Aplica a contribuyentes que cumplan con los requisitos establecidos en la LIR.",
  },
  {
    fieldCode: 1163,
    name: "Rebaja FUR por devolución de capital y enajenación",
    legalBasis: "Artículo 21 de la Ley sobre Impuesto a la Renta",
    limitType: "none",
    strategy: "Considerar la planificación de enajenaciones y reorganizaciones para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que realicen devoluciones de capital, enajenaciones o reorganizaciones empresariales.",
  },
  {
    fieldCode: 1164,
    name: "Rebaja FUR por devolución de capital, enajenación de acciones o reorganización empresarial",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar la correcta imputación de las rentas registradas en el FUR para optimizar la carga tributaria.",
    conditions: "Contribuyentes que se acojan al Impuesto de Primera Categoría (IS) y realicen las operaciones mencionadas.",
  },
  {
    fieldCode: 1172,
    name: "Crédito por IDPC utilizado en el ejercicio",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Aprovechar el crédito por IDPC para reducir la carga tributaria en el ejercicio correspondiente. Es recomendable llevar un control adecuado de los créditos disponibles para su correcta imputación.",
    conditions: "Contribuyentes que hayan generado créditos por IDPC en el año comercial 2025.",
  },
  {
    fieldCode: 1176,
    name: "Castigo de deudas incobrables",
    legalBasis: "artículo 31, inciso 4°, N° 4 LIR",
    limitType: "none",
    strategy: "Considerar el castigo de deudas incobrables como un gasto necesario para la producción de renta. Asegurarse de documentar adecuadamente el proceso de cobranza previo al castigo.",
    conditions: "Contribuyentes que hayan agotado los medios de cobro o que opten por la vía alternativa para créditos impagos por más de 365 días.",
  },
  {
    fieldCode: 1179,
    name: "Pérdida por rentas exentas del IDPC e INR",
    legalBasis: "Artículo 31 LIR",
    limitType: "none",
    strategy: "Considerar la diferencia negativa entre rentas exentas e ingresos no renta y los costos asociados para optimizar la carga tributaria.",
    conditions: "Aplicable a empresas que generen rentas exentas de IDPC e INR.",
  },
  {
    fieldCode: 1190,
    name: "Otras partidas a deducir",
    legalBasis: "Circulares N° 39 de 2022 y N° 31 de 2023",
    limitType: "none",
    strategy: "Considerar todas las partidas que no estén incluidas en otros códigos para maximizar deducciones.",
    conditions: "Aplicable a contribuyentes que tengan partidas deducibles no registradas en otros códigos.",
  },
  {
    fieldCode: 1214,
    name: "Reverso y/o disminuciones del ejercicio (propios)",
    legalBasis: "Artículo 31 LIR",
    limitType: "none",
    strategy: "Considerar la depreciación normal después de la acelerada para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que hayan realizado depreciación acelerada previamente.",
  },
  {
    fieldCode: 1268,
    name: "Retiros en exceso y devoluciones de capital",
    legalBasis: "N° 6.2 y N° 6.3 del anexo N° 1",
    limitType: "none",
    strategy: "Considerar la imputación de retiros en exceso y devoluciones de capital para optimizar la carga tributaria en el ejercicio correspondiente.",
    conditions: "Aplicable a contribuyentes que hayan asignado crédito por IDPC acumulado hasta el 31.12.2016.",
  },
  {
    fieldCode: 1363,
    name: "Crédito no sujeto a restitución",
    legalBasis: "artículo 14 de la LIR",
    limitType: "percentage_of_field",
    referenceField: 1360,
    strategy: "Aprovechar el crédito asignado en proporción a la base imponible para optimizar la carga tributaria.",
    conditions: "Propietarios que ingresaron al régimen del N° 8 de la letra D) del artículo 14 de la LIR.",
  },
  {
    fieldCode: 1364,
    name: "Crédito sujeto a restitución",
    legalBasis: "artículo 14 de la LIR",
    limitType: "percentage_of_field",
    referenceField: 1361,
    strategy: "Asigne el crédito a los propietarios en proporción a la base imponible del año comercial correspondiente para optimizar la imputación a los impuestos finales.",
    conditions: "Propietarios que ingresaron al régimen del N° 8 de la letra D) del artículo 14 de la LIR.",
  },
  {
    fieldCode: 1378,
    name: "Pérdida por rentas exentas e ingresos no renta",
    legalBasis: "Artículo 31 LIR",
    limitType: "none",
    strategy: "Considerar la correcta identificación de las rentas exentas y los costos asociados para maximizar la deducción.",
    conditions: "Aplicable a empresas que generen rentas exentas de IDPC e INR.",
  },
  {
    fieldCode: 1381,
    name: "Otras partidas a deducir",
    legalBasis: "Circulares N° 39 de 2022 y N° 31 de 2023",
    limitType: "none",
    strategy: "Considerar las disminuciones de capital y otros valores negativos para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que realicen reorganizaciones empresariales.",
  },
  {
    fieldCode: 1432,
    name: "Incentivo al ahorro",
    legalBasis: "art. 14 letra E) LIR",
    limitType: "fixed_uf",
    limitValue: 5000,
    strategy: "Considerar el monto deducido de acuerdo al incentivo al ahorro para optimizar la base imponible.",
    conditions: "Aplicable a contribuyentes que mantengan inversión en la empresa.",
  },
  {
    fieldCode: 1578,
    name: "Crédito por IDPC",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar el crédito por IDPC al momento de calcular la carga tributaria total. Asegurarse de registrar correctamente el monto en el código 1605 del F-22.",
    conditions: "Aplicable a contribuyentes que hayan incrementado la base imponible del ejercicio a través de participaciones en otras empresas.",
  },
  {
    fieldCode: 1582,
    name: "CPT o CPTS negativo inicial",
    legalBasis: "artículo 14, letra A), D) de la LIR",
    limitType: "none",
    strategy: "Registrar el valor correspondiente del formulario anterior para determinar el CPT o CPTS negativo inicial.",
    conditions: "Contribuyentes acogidos al régimen del artículo 14, letra A), D) N° 3 o D) N° 8 de la LIR.",
  },
  {
    fieldCode: 1585,
    name: "Otras partidas a deducir",
    legalBasis: "Circulares N° 39 de 2022 y N° 31 de 2023",
    limitType: "none",
    strategy: "Considerar las disminuciones efectivas de capital y otros valores negativos para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que realicen reorganizaciones empresariales.",
  },
  {
    fieldCode: 1653,
    name: "Crédito imputado en el ejercicio",
    legalBasis: "Artículo LIR",
    limitType: "percentage_of_income",
    limitValue: 0.65,
    strategy: "Considerar el crédito asociado al ingreso diferido y su imputación en el año comercial correspondiente para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que reconozcan ingresos diferidos.",
  },
  {
    fieldCode: 1661,
    name: "Costo directo de bienes y servicios",
    legalBasis: "artículo 107 de la LIR",
    limitType: "none",
    strategy: "Registrar el costo directo de producción o comercialización de bienes y servicios del giro del contribuyente para reducir la base imponible.",
    conditions: "Contribuyentes que registren ingresos por actividades habituales o normales.",
  },
  {
    fieldCode: 1662,
    name: "Remuneraciones",
    legalBasis: "artículo 31 de la Ley sobre Impuesto a la Renta",
    limitType: "none",
    strategy: "Considerar todas las remuneraciones pagadas o adeudadas a los trabajadores como deducción para reducir la base imponible.",
    conditions: "Aplica a todos los contribuyentes que registren remuneraciones en sus estados financieros.",
  },
  {
    fieldCode: 1663,
    name: "Depreciación financiera del ejercicio",
    legalBasis: "Artículo 31 LIR",
    limitType: "none",
    strategy: "Registrar la depreciación financiera de los activos inmovilizados para reducir la base imponible. Asegúrese de que esté debidamente contabilizada.",
    conditions: "Contribuyentes que utilizan bienes físicos en su actividad económica.",
  },
  {
    fieldCode: 1664,
    name: "Intereses pagados o adeudados",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considera los intereses pagados o adeudados para financiar actividades productivas como deducción en tu declaración de impuestos.",
    conditions: "Contribuyentes que generen renta en el ejercicio o en futuros ejercicios.",
  },
  {
    fieldCode: 1665,
    name: "Gastos por donaciones",
    legalBasis: "Artículo 31, inciso 4°, N° 7, de la LIR y otras leyes mencionadas",
    limitType: "none",
    strategy: "Considera realizar donaciones a entidades que califiquen para beneficios tributarios para maximizar deducciones.",
    conditions: "Contribuyentes que realicen donaciones en el año comercial 2025.",
  },
  {
    fieldCode: 1666,
    name: "Otros gastos financieros",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar todos los gastos financieros no incluidos en otros códigos para maximizar deducciones.",
    conditions: "Aplicable a todos los contribuyentes que incurran en estos gastos.",
  },
  {
    fieldCode: 1667,
    name: "Gastos en I+D certificados por CORFO",
    legalBasis: "artículos 4° y 9° de la Ley N° 20.241",
    limitType: "none",
    strategy: "Considerar la amortización de los gastos en I+D a lo largo de diez ejercicios comerciales para optimizar la carga tributaria.",
    conditions: "Contribuyentes que hayan obtenido certificación de CORFO",
  },
  {
    fieldCode: 1668,
    name: "Gastos por inversión en I+D no certificados",
    legalBasis: "artículos 4° y 9° de la Ley N° 20.241",
    limitType: "percentage_of_income",
    limitValue: 0.65,
    strategy: "Considerar la opción de amortizar los gastos en diez ejercicios comerciales para optimizar la deducción fiscal.",
    conditions: "Contribuyentes que incurren en gastos de I+D no certificados por CORFO.",
  },
  {
    fieldCode: 1669,
    name: "Costos y gastos para rentas de fuente extranjera",
    legalBasis: "artículo 41 B de la LIR",
    limitType: "percentage_of_income",
    referenceField: 1658,
    strategy: "Registrar los costos y gastos necesarios para la generación de rentas de fuente extranjera para optimizar la carga tributaria.",
    conditions: "Contribuyentes con EP en el exterior",
  },
  {
    fieldCode: 1670,
    name: "Gastos por impuesto renta e impuesto diferido",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar la contabilización adecuada de los gastos por impuesto a la renta y diferido para optimizar la carga tributaria.",
  },
  {
    fieldCode: 1671,
    name: "Otros gastos deducidos de los ingresos brutos",
    legalBasis: "artículo 107 de la LIR",
    limitType: "none",
    strategy: "Registrar todos los gastos necesarios para producir la renta que no estén incluidos en otros códigos. Asegurarse de incluir el costo tributario de acciones y cuotas enajenadas o rescatadas.",
    conditions: "Aplicable a contribuyentes que hayan registrado ingresos en los códigos 1657, 1658, 1659 y 1660.",
  },
  {
    fieldCode: 1679,
    name: "Depreciación tributaria del ejercicio",
    legalBasis: "artículo 31 de la LIR",
    limitType: "none",
    strategy: "Aprovechar la depreciación tributaria para reducir la base imponible del impuesto a la renta. Asegúrese de registrar correctamente las depreciaciones aceleradas en los códigos correspondientes.",
    conditions: "Contribuyentes que posean bienes físicos del activo inmovilizado",
  },
  {
    fieldCode: 1680,
    name: "Gasto goodwill tributario del ejercicio",
    legalBasis: "artículo 31 de la LIR",
    limitType: "none",
    strategy: "Considerar la cuota anual de goodwill tributario para optimizar la RLI.",
    conditions: "Aplicable a contribuyentes que registren goodwill tributario.",
  },
  {
    fieldCode: 1681,
    name: "Impuesto específico a la actividad minera",
    legalBasis: "artículo 31 de la LIR",
    limitType: "none",
    strategy: "Considerar el impuesto específico a la actividad minera como un gasto deducible al calcular la RLI para optimizar la carga tributaria.",
    conditions: "Contribuyentes que sean explotadores mineros y estén sujetos a regímenes de invariabilidad tributaria.",
  },
  {
    fieldCode: 1682,
    name: "Gastos rechazados afectos a la tributación del art. 21 inc. 1° LIR",
    legalBasis: "artículo 21 LIR",
    limitType: "none",
    strategy: "Considerar los gastos rechazados que han sido agregados a la renta líquida para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que registren gastos rechazados en los códigos 1677 y/o 1678.",
  },
  {
    fieldCode: 1683,
    name: "Gastos rechazados afectos a IGC o IA",
    legalBasis: "artículo 21 inc. 3° LIR",
    limitType: "none",
    strategy: "Considerar los gastos rechazados para calcular la base imponible, independientemente de su registro contable. Asegurarse de que estén correctamente documentados.",
    conditions: "Aplicable a contribuyentes afectos a IGC o IA",
  },
  {
    fieldCode: 1684,
    name: "Otras partidas deducibles",
    legalBasis: "artículo 107 de la LIR",
    limitType: "none",
    strategy: "Registrar ajustes por diferencias entre normas financieras y tributarias para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que realicen enajenaciones de acciones o cuotas de fondos en el año comercial.",
  },
  {
    fieldCode: 1685,
    name: "Rentas exentas IDPC",
    legalBasis: "art. 33 N°2 LIR",
    limitType: "none",
    strategy: "Considerar las rentas exentas de IDPC al momento de calcular los ingresos brutos para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que perciban rentas exentas conforme a la LIR y otras leyes especiales.",
  },
  {
    fieldCode: 1687,
    name: "Gastos aceptados por donaciones",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar las donaciones como gastos necesarios para la producción de renta puede optimizar la carga tributaria. Es recomendable llevar un registro detallado de las donaciones realizadas.",
    conditions: "Cualquier contribuyente que realice donaciones aceptadas según la normativa vigente.",
  },
  {
    fieldCode: 1689,
    name: "Pérdidas de ejercicios anteriores",
    legalBasis: "art. 31 N° 3 LIR",
    limitType: "none",
    strategy: "Las pérdidas de ejercicios anteriores pueden ser utilizadas para reducir la base imponible en ejercicios futuros, optimizando así la carga tributaria. Es recomendable llevar un registro detallado de las pérdidas para su correcta aplicación.",
    conditions: "Contribuyentes que hayan tenido pérdidas tributarias en ejercicios anteriores.",
  },
  {
    fieldCode: 1695,
    name: "Pérdida tributaria del ejercicio",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar la pérdida tributaria para optimizar la carga impositiva en ejercicios futuros.",
    conditions: "Aplicable a contribuyentes que hayan registrado pérdidas en el ejercicio.",
  },
  {
    fieldCode: 1697,
    name: "Partidas no afectas al IU de tasa 40%",
    legalBasis: "artículo 21 LIR",
    limitType: "none",
    strategy: "Considerar las partidas no afectas al impuesto de primera categoría para optimizar la carga tributaria.",
    conditions: "Contribuyentes que registren partidas del inciso primero y segundo del artículo 21 LIR.",
  },
  {
    fieldCode: 1706,
    name: "Pérdida tributaria del ejercicio",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar la pérdida tributaria para optimizar la carga impositiva en ejercicios futuros.",
    conditions: "Contribuyentes que hayan registrado pérdidas tributarias en el ejercicio.",
  },
  {
    fieldCode: 1713,
    name: "Pérdida tributaria del ejercicio",
    legalBasis: "Artículo 31 LIR",
    limitType: "none",
    strategy: "Considerar la pérdida tributaria para reducir la base imponible en ejercicios futuros. Planificar el uso de pérdidas para optimizar la carga tributaria.",
    conditions: "Contribuyentes que hayan generado pérdidas tributarias en el ejercicio.",
  },
  {
    fieldCode: 1716,
    name: "Crédito por activos fijos adquiridos",
    legalBasis: "art. 33 bis LIR",
    limitType: "none",
    strategy: "Considerar la adquisición de activos fijos para maximizar el crédito tributario disponible.",
    conditions: "Contribuyentes que adquieran activos fijos en el ejercicio.",
  },
  {
    fieldCode: 1965,
    name: "Cuota depreciación normal",
    legalBasis: "artículo LIR",
    limitType: "none",
    strategy: "Considerar la depreciación normal como un gasto deducible para optimizar la carga tributaria.",
    conditions: "Aplicable a contribuyentes que registren activos fijos en su contabilidad.",
  },
  {
    fieldCode: 1966,
    name: "Cuota gastos de organización y puesta en marcha",
    legalBasis: "artículo 31 de la LIR",
    limitType: "none",
    strategy: "Considerar la deducción de un sexto de los gastos de organización y puesta en marcha para optimizar la carga tributaria.",
  },
  {
    fieldCode: 1974,
    name: "Componente ad valorem del royalty minero",
    legalBasis: "artículo 31 de la LIR",
    limitType: "none",
    strategy: "Considerar el componente ad valorem del royalty minero al calcular la RLI para optimizar la carga tributaria.",
    conditions: "Contribuyentes que generen ingresos por actividades mineras.",
  },
  {
    fieldCode: 1975,
    name: "Componente sobre la rentabilidad del royalty minero",
    legalBasis: "artículo 3 o 4 Ley N° 21.591",
    limitType: "none",
    strategy: "Considerar el componente sobre la rentabilidad del royalty minero al calcular la RLI para optimizar la carga tributaria. Asegurarse de ajustar al LCTMP cuando corresponda.",
    conditions: "Contribuyentes que devengan el royalty minero según la Ley N° 21.591",
  },
  {
    fieldCode: 1983,
    name: "Valor de adquisición de bienes raíces reajustados",
    legalBasis: "artículo 17 de la LIR",
    limitType: "none",
    strategy: "Considerar el valor de adquisición reajustado hasta el 31.12.2025 para optimizar la carga tributaria al enajenar bienes raíces.",
    conditions: "Aplicable a bienes raíces adquiridos entre el 1° de enero de 2004 y el 28 de septiembre de 2014, cumpliendo requisitos de la Ley N° 20.780.",
  },
  {
    fieldCode: 1984,
    name: "Valor de adquisición de bienes raíces reajustados",
    legalBasis: "artículo 17 de la LIR",
    limitType: "none",
    strategy: "Asegúrate de reajustar correctamente el valor de adquisición hasta el 31.12.2025 para maximizar la deducción.",
    conditions: "Aplicable a bienes raíces poseídos en CM, adjudicados en partición hereditaria o liquidación de sociedades.",
  },
  {
    fieldCode: 1986,
    name: "Mejoras que aumentan el valor de bienes raíces",
    legalBasis: "artículo 17 de la LIR",
    limitType: "none",
    strategy: "Registrar las mejoras que aumenten el valor de los bienes raíces para optimizar la deducción tributaria.",
    conditions: "Aplicable a bienes raíces situados en Chile enajenados a un no relacionado.",
  },
];

export function getDeductibleFieldMap(): Map<number, DeductibleField[]> {
  const map = new Map<number, DeductibleField[]>();
  for (const df of DEDUCTIBLE_FIELDS) {
    const existing = map.get(df.fieldCode) ?? [];
    existing.push(df);
    map.set(df.fieldCode, existing);
  }
  return map;
}
